CREATE TYPE [ems_data].[logger_data_type] AS TABLE(
	[ABST] [varchar](20) NULL,
	[ADOP] [varchar](20) NULL,
	[AID] [varchar](20) NULL,
	[AMFR] [varchar](20) NULL,
	[AMOD] [varchar](20) NULL,
	[APQS] [varchar](20) NULL,
	[ASER] [varchar](20) NULL,
	[CDAT] [varchar](20) NULL,
	[CID] [varchar](20) NULL,
	[CNAM] [varchar](20) NULL,
	[CSER] [varchar](20) NULL,
	[CSOF] [varchar](20) NULL,
	[DNAM] [varchar](20) NULL,
	[EDOP] [varchar](20) NULL,
	[EID] [varchar](20) NULL,
	[EMFR] [varchar](20) NULL,
	[EMOD] [varchar](20) NULL,
	[EMSV] [varchar](20) NULL,
	[EPQS] [varchar](20) NULL,
	[ESER] [varchar](20) NULL,
	[FID] [varchar](20) NULL,
	[FNAM] [varchar](20) NULL,
	[LDOP] [varchar](20) NULL,
	[LID] [varchar](20) NULL,
	[LMFR] [varchar](20) NULL,
	[LMOD] [varchar](20) NULL,
	[LPQS] [varchar](20) NULL,
	[LSER] [varchar](20) NULL,
	[LSV] [varchar](20) NULL,
	[RNAM] [varchar](20) NULL,
	[ACCD] [decimal](4, 2) NULL,
	[ACSV] [decimal](4, 1) NULL,
	[ALRM] [varchar](20) NULL,
	[BEMD] [decimal](5, 1) NULL,
	[BLOG] [int] NULL,
	[CMPR] [int] NULL,
	[CMPS] [int] NULL,
	[DCCD] [decimal](3, 1) NULL,
	[DCSV] [decimal](4, 1) NULL,
	[DORF] [int] NULL,
	[DORV] [int] NULL,
	[EERR] [varchar](20) NULL,
	[FANS] [decimal](3, 1) NULL,
	[HAMB] [decimal](3, 1) NULL,
	[HCOM] [decimal](3, 1) NULL,
	[HOLD] [decimal](4, 1) NULL,
	[LAT] [decimal](6, 3) NULL,
	[LERR] [varchar](20) NULL,
	[LNG] [decimal](6, 3) NULL,
	[MSW] [tinyint] NULL,
	[RELT] [varchar](20) NULL,
	[RTCW] [varchar](20) NULL,
	[SVA] [int] NULL,
	[TAMB] [decimal](5, 2) NULL,
	[TCON] [decimal](5, 2) NULL,
	[TFRZ] [decimal](5, 2) NULL,
	[TPCB] [decimal](5, 2) NULL,
	[TVC] [decimal](5, 2) NULL,
	[duration_secs] [varchar](20) NULL,
	[utc_timestamp] [varchar](20) NULL
)
GO