CREATE TABLE [varo].[location] (
    [ASER]        VARCHAR (20)   NOT NULL,
    [REPORTTIME]  DATETIME2 (0)  NOT NULL,
    [ACCURACY]    DECIMAL (8, 5) NULL,
    [LATITUDE]    DECIMAL (8, 5) NULL,
    [LONGITUDE]   DECIMAL (8, 5) NULL,
    [DATEADDED]   DATETIME2 (0)  NULL,
    [DATEUPDATED] DATETIME2 (0)  NULL,
    CONSTRAINT [PK_varo_location] PRIMARY KEY CLUSTERED ([ASER] ASC, [REPORTTIME] ASC)
);

