CREATE TYPE [sl1].[event_type] AS TABLE (
    [ABST_CALC]  DATETIME2 (7)  NOT NULL,
    [ADOP]       VARCHAR (100)  NULL,
    [ALRM]       VARCHAR (100)  NULL,
    [AMOD]       VARCHAR (100)  NULL,
    [AMFR]       VARCHAR (100)  NULL,
    [APQS]       VARCHAR (20)   NULL,
    [ASER]       VARCHAR (50)   NULL,
    [BLOG]       DECIMAL (5, 1) NULL,
    [ESER]       VARCHAR (50)   NULL,
    [LDOP]       VARCHAR (100)  NULL,
    [LERR]       VARCHAR (20)   NULL,
    [LMFR]       VARCHAR (20)   NULL,
    [LMOD]       VARCHAR (20)   NULL,
    [LPQS]       VARCHAR (20)   NULL,
    [LSER]       VARCHAR (50)   NOT NULL,
    [LSV]        VARCHAR (20)   NULL,
    [RELT]       VARCHAR (20)   NOT NULL,
    [RTCW]       VARCHAR (20)   NULL,
    [TAMB]       NUMERIC (5, 2) NULL,
    [TVC]        NUMERIC (5, 2) NULL,
    [ZCHRG]      VARCHAR (10)   NULL,
    [ZSTATE]     BIT            NULL,
    [ZVLVD]      BIT            NULL,
    [CNAM]       VARCHAR (50)   NULL,
    [CSER]       VARCHAR (50)   NULL,
    [CSOF]       VARCHAR (50)   NULL,
    [CMPR]       TINYINT        NULL,
    [CMPS]       SMALLINT       NULL,
    [DCCD]       NUMERIC (3, 1) NULL,
    [DCSV]       NUMERIC (4, 1) NULL,
    [FANS]       NUMERIC (4, 1) NULL,
    [SVA]        SMALLINT       NULL,
    [DORV]       SMALLINT       NULL,
    [DORF]       SMALLINT       NULL,
    [TFRZ]       NUMERIC (5, 2) NULL,
    [_RELT_SECS] VARCHAR (20)   NULL);



